### ISSUE TITLE
メールよりこっちの方がいいですかね？

### ISSUE THREAD

**Issue by yuyabee** [Azabuhs/Talking#2]
多分メールよりこっちの方がいいかなって思ったので、普通のチャットみたいに使っちゃいます。

@gogotanaka 今日は伺っても大丈夫ですか？

**Comment by gogotanaka** [comment]
あれメールくれてた？ごめん ;( 

明日ならオフィス居るよ！！

**Comment by yuyabee** [comment]
どうかお気になさらずに。
明日はCEOもいらっしゃるんですか？一度話してみたいです。

TwitterのDMとかの方が良かったりします？

**Comment by gogotanaka** [comment]
twitter にしよう https://twitter.com/gogo_tanaka
